server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: DISCOVERY-SERVER
          # uri: http://localhost:8761
          uri: http://eureka-server-service.java-aws-microservice.svc.cluster.local:8761
          predicates:
            - Path=/eureka/web/**
          filters:
            - SetPath=/

        - id: DISCOVERY-SERVER-STATIC
          # uri: http://localhost:8761
          uri: http://eureka-server-service.java-aws-microservice.svc.cluster.local:8761
          predicates:
            - Path=/eureka/**

        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        - id: ORDER-SERVICE
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server-service.java-aws-microservice.svc.cluster.local:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: api-gateway-service.java-aws-microservice.svc.cluster.local
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


  
