server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
  gateway:
    routes:
      - id: user-service-service
        uri: lb://user-service-service
        predicates:
          - Path=/api/user/**

      - id: order-service-service
        uri: lb://order-service-service
        predicates:
          - Path=/api/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


  
