apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: java-aws-microservice
  labels:
    app: user-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server-service.java-aws-microservice.svc.cluster.local:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "user-service-service.java-aws-microservice.svc.cluster.local"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: java-aws-microservice
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP