server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server-service.java-aws-microservice.svc.cluster.local:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: user-service-service.java-aws-microservice.svc.cluster.local
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}